### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by osbyrne** [lucadonnoh/scalability_guide#3]
I try to read your post about light clients and server says: Internal Server Error - Request ID: 01GH1DE6PK5YJ8BKKKA6S1K44C

**Comment by lucadonnoh** [comment]
hey, thank you for reporting this! on my end the site seems to work fine with [this link](https://scalability.guide/posts/maximising_light_clients_security/) and at first glance i don’t see any issue on the hosting website but i’ll try to investigate deeper, let me know if you manage to solve the problem on your end

**Comment by osbyrne** [comment]
website seems to work fine now! no issues. sorry for the spam
